spring:
  datasource:
    url: jdbc:mysql://storemanagementmysql:3306/storemanagement?serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
server:
  port: 8085
  servlet:
    context-path: /store-management
logging:
  file:
    name: /store-management/store-management.log
